### ISSUE TITLE
賃金台帳でその他調整額の合計が表示されていない

### ISSUE THREAD

**Issue by ichylinux** [hybitz/hyacc#34]
賃金台帳でその他調整額の合計が表示されておらず、結果として、差引合計額の値がずれていると思われる。

**Comment by ichylinux** [comment]
@aomrikti 

表題の件、現象を確認するに至るまで、開発環境で画面操作を行ってみてください。
画面操作をしている中で、マスタデータの不備などをきちんとハンドリングできてなくてエラー画面になることがあるかもしれません。
それらはIssueの起票をお願いします。

まずは、アプリに慣れる目的で、画面操作を確認いただくところまでをお願いします。

**Comment by ichylinux** [comment]
@aomrikti 

本件対応しましたので、対応内容に疑問点がないか、レビューをお願いします。

**Comment by aomrikti** [comment]
@ichylinux 
下記のとおり賃金台帳で「その他調整額」の合計が表示されることを確認しました。
（実際の賃金台帳についても表示を確認しました。）
それでは本件、クローズします。
ご対応ありがとうございました。

- 「その他調整額」の入力前
![スクリーンショット 2024-12-04 182847](https://github.com/user-attachments/assets/44d12a7f-e6f9-42cb-bf15-1e980bd6a6da)
- 「その他調整額」の入力後
![image](https://github.com/user-attachments/assets/c95001e0-220c-4fb3-8769-8455ce5205cc)
